apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eedhk35zj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eedhk35zj-nodejs 
  name: eedhk35zj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: eedhk35zj-nodejs 
