apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eedhk35zj-nodejs 
  janus-idp.io/tekton: eedhk35zj-nodejs
  backstage.io/kubernetes-id: eedhk35zj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eedhk35zj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml